#!/usr/bin/env bash
# Dev-environment setup for qa-framework.
#
# The framework RUNTIME is zero-dependency: `python3 -m engine.run --sut <site>` (and the
# whole `make demo` / `make test` flow) works with no install at all. This script installs
# only the DEV / TEST toolchain — pytest, pytest-xdist, ruff (lint), pip-audit (CVE scan) —
# via Poetry into a project-local ./.venv. Run it with `make install`.
set -euo pipefail
cd "$(dirname "$0")/.."

if ! command -v poetry >/dev/null 2>&1; then
  cat >&2 <<'EOF'
  Poetry is not installed — it manages this project's dev/test dependencies.
  Install it first, then re-run `make install`:

    pipx install poetry                                   # recommended (isolated)
    # or the official installer:
    curl -sSL https://install.python-poetry.org | python3 -
    # or, quick-and-dirty:
    python3 -m pip install --user poetry
EOF
  exit 1
fi

echo "==> poetry install (pytest, pytest-xdist, ruff, pip-audit, playwright -> ./.venv)"
poetry install

echo "==> playwright install chromium (the browser the UI lane drives; ~150MB)"
poetry run playwright install chromium

cat <<'EOF'
==> dev toolchain ready. Common commands:
      make pytest    # REST + unit tests in parallel (pytest -n auto)
      make test-ui   # browser (Playwright) UI packs, headless
      make ui-watch  # watch the UI verification live (headed, slowed-down)
      make lint      # ruff lint
      make cve       # pip-audit dependency CVE scan
      make verify    # lint + cve + pytest + the offline gates
    (or run any of them directly with `poetry run <tool>`)
EOF

# --------------------------------------------------------------------------
# Claude Code integration (opt-in, project-scoped)
#
# Qensei is driven by an AI coding assistant. Its slash commands (commands/),
# review-panel subagents (agents/), and governance (policies/) only become
# discoverable once they live under ./.claude — Claude Code scans .claude/commands
# and .claude/agents at project scope. This step SYMLINKS them there, so the repo
# root stays the single source of truth (edits are live, no re-sync) and generates
# a ./.claude/CLAUDE.md that references the policies as governance.
#
# Project-scoped and opt-in: nothing is written to ~/.claude. ./.claude is
# gitignored, so the wiring is a local artifact — re-run `make install` to refresh.
# Set QENSEI_CLAUDE_WIRING=y to enable non-interactively (CI defaults to skip).
# --------------------------------------------------------------------------

# Generate ./.claude/CLAUDE.md (governance index). Paths are repo-root-relative:
# Claude Code runs with the repo root as cwd, so the assistant opens policies/… directly.
generate_claude_md() {
  cat <<'MD'
# Qensei — project instructions (generated by scripts/install.sh; do not hand-edit)

Qensei is an AI-assistant-driven QA framework. This file wires its governance into
Claude Code at project scope. It is regenerated by `make install`; the source of truth
is `policies/`, `commands/`, and `agents/` at the repo root.

## Governance — apply the policies in `policies/`
Product-neutral development governance. Read the relevant file when it applies:
- `policies/methodology.md` — spec-driven QA phases, spec conventions, ownership model
- `policies/testing-philosophy.md` — tests as behavioral contracts; real-downstream AC at integration boundaries
- `policies/communication-standards.md` — factual, neutral authoring for durable artifacts
- `policies/security-review.md` — mandatory dependency CVE scan + OWASP review
- `policies/input-hygiene.md` — credential/display/log hygiene
- `policies/release-safety.md` — reversibility / rollback discipline
- `policies/python-standards.md` — Python coding standards
- `policies/git-workflow.md` — commit/branch conventions (no AI-attribution trailers)

## Slash commands (`./.claude/commands` → `../commands`)
- `/automate` — turn a manually-tested ticket into an intent spec + regression pack
- `/validate` — verify a ticket over REST or UI
- `/report-bug` — file a structured bug for a genuine backend regression

## Review panel — subagents (`./.claude/agents` → `../agents`)
Advisory, read-only diagnostic lenses: `judge`, `r-diagnosis`, `r-evidence`,
`r-fidelity`, `r-coverage`, `r-mechanism`, `r-uplift`. They raise the floor; they never gate a merge.

## Domain knowledge — per SUT, loaded on demand (NOT loaded here)
Each product under test is a plugin under `sut/<name>/`. Its domain/system-shape
knowledge lives in `sut/<name>/skills/*.md` and accumulated `sut/<name>/learnings/*.md`,
declared in `sut/<name>/manifest.json` (`knowledge.skills` / `knowledge.learnings`).
These are intentionally NOT referenced globally: `/automate` and `/validate` load the
ACTIVE SUT's skills + learnings based on `--sut`, so only the relevant product's
knowledge enters context. Do not hardcode one SUT's skills in this file.

Discovered SUT skills:
MD
  local skill sut_name found=0
  for skill in sut/*/skills/*.md; do
    [ -f "$skill" ] || continue
    sut_name=$(basename "$(dirname "$(dirname "$skill")")")
    echo "- \`$sut_name\` — \`$skill\`"
    found=1
  done
  [ "$found" -eq 1 ] || echo "- (none discovered under sut/*/skills/)"
}

install_claude_wiring() {
  mkdir -p .claude
  ln -sfn ../commands .claude/commands
  ln -sfn ../agents   .claude/agents
  generate_claude_md > .claude/CLAUDE.md
  echo "  ./.claude/commands -> ../commands   (/automate, /validate, /report-bug)"
  echo "  ./.claude/agents   -> ../agents     (review panel: judge + r-* lenses)"
  echo "  ./.claude/CLAUDE.md                 (governance: policies/ + per-SUT skills pointer)"
  echo "  ./.claude is gitignored — re-run 'make install' to refresh the wiring."
  echo "  NOTE: (re)start Claude Code after first wiring so the review-panel lenses load"
  echo "        read-only — their tools: allowlist is applied at session start, not mid-session."
}

echo
if [ "${QENSEI_CLAUDE_WIRING:-}" = "y" ]; then
  reply="y"
elif [ -t 0 ]; then
  printf "==> Wire Qensei's commands, agents and policies into Claude Code (project-scoped ./.claude, symlinked)? [y/N] "
  read -r reply
else
  reply="n"   # non-interactive (CI): skip unless QENSEI_CLAUDE_WIRING=y
fi
case "$reply" in
  [Yy]*)
    echo "==> installing Claude Code integration (./.claude, symlinked to the repo root)"
    install_claude_wiring
    ;;
  *)
    echo "==> skipped Claude Code integration (re-run 'make install', or set QENSEI_CLAUDE_WIRING=y)"
    ;;
esac
