"""Aggregate per-pack index cards into one generated index — ``make regen-index``.

Each ``packs/<id>/README.md`` is the "card future agents read first": its H1
(``# <pack-id> — <title>  · <status>``) plus its first paragraph. This rolls them all,
sorted by pack-id, into a generated ``docs/delivered-regressions.md`` so the suite has a
single browseable index without a central file growing per-test (t-800's regen-index).
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "delivered-regressions.md"

HEADER = (
    "# Delivered regressions (generated)\n\n"
    "> Generated by `make regen-index` (scripts/regen_index.py) from each pack's README "
    "index card. Do not edit by hand — edit the pack README and regenerate.\n\n"
)


def _card(readme: Path) -> str:
    lines = readme.read_text().splitlines()
    h1 = next((ln for ln in lines if ln.startswith("# ")), f"# {readme.parent.name}")
    rest = lines[lines.index(h1) + 1 :] if h1 in lines else lines
    para = []
    for ln in rest:
        if ln.strip() and not ln.startswith("#"):
            para.append(ln.strip())
        elif para:
            break
    summary = " ".join(para)
    return f"### {h1[2:].strip()}\n\n{summary}\n\n[`packs/{readme.parent.name}/`](../packs/{readme.parent.name}/README.md)\n"


def main() -> int:
    readmes = sorted(ROOT.glob("packs/*/README.md"), key=lambda p: p.parent.name)
    body = HEADER + "\n".join(_card(r) for r in readmes)
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(body + "\n")
    print(f"  wrote {OUT.relative_to(ROOT)} ({len(readmes)} pack card(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
