"""Aggregate per-pack index cards into one generated index — ``make regen-index``.

Each ``sut/<site>/packs/<id>/README.md`` is the "card future agents read first": its H1
(``# <pack-id> — <title>  · <status>``) plus its first paragraph. This rolls them all,
grouped by SITE then sorted by pack-id, into a generated ``docs/delivered-regressions.md``
so the multi-site suite has a single browseable index without a central file growing
per-test.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "delivered-regressions.md"

HEADER = (
    "# Delivered regressions (generated)\n\n"
    "> Generated by `make regen-index` (scripts/regen_index.py) from each pack's README "
    "index card, grouped by site. Do not edit by hand — edit the pack README and regenerate.\n\n"
)


def _card(readme: Path) -> str:
    lines = readme.read_text().splitlines()
    h1 = next((ln for ln in lines if ln.startswith("# ")), f"# {readme.parent.name}")
    rest = lines[lines.index(h1) + 1 :] if h1 in lines else lines
    para = []
    for ln in rest:
        if ln.strip() and not ln.startswith("#"):
            para.append(ln.strip())
        elif para:
            break
    summary = " ".join(para)
    site, pack_type = readme.parents[2].name, readme.parents[1].name  # ".../<site>/<packs|ui-packs>/<id>/README.md"
    rel = f"sut/{site}/{pack_type}/{readme.parent.name}"
    return f"### {h1[2:].strip()}\n\n{summary}\n\n[`{rel}/`](../{rel}/README.md)\n"


def main() -> int:
    readmes = sorted(
        list(ROOT.glob("sut/*/packs/*/README.md")) + list(ROOT.glob("sut/*/ui-packs/*/README.md")),
        key=lambda p: (p.parents[2].name, p.parents[1].name, p.parent.name),
    )
    sites: dict[str, list[Path]] = {}
    for r in readmes:
        sites.setdefault(r.parents[2].name, []).append(r)

    sections = []
    for site in sorted(sites):
        cards = "\n".join(_card(r) for r in sites[site])
        sections.append(f"## Site: `{site}`\n\n{cards}")
    body = HEADER + "\n".join(sections)
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(body + "\n")
    print(f"  wrote {OUT.relative_to(ROOT)} ({len(readmes)} pack card(s) across {len(sites)} site(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
